function getexpr(Tdist)
    x = gensym()
    fnames = fieldnames(Tdist)
    flattened_args = Expr(:tuple, [:(dist.$f) for f in fnames]...)
    func = Expr(:->, 
                Expr(:tuple, fnames..., x), 
                Expr(:block,
                    Expr(:call, :logpdf,
                        Expr(:call, :($Tdist), fnames...),
                        x,
                    )
                )
            )
    return :(flatten(dist::$Tdist) = ($func, $flattened_args))
end
for T in (  Bernoulli,
            BetaBinomial,
            Binomial,
            Geometric,
            NegativeBinomial,
            Poisson,
            Skellam,
            PoissonBinomial,
            Arcsine,
            BetaBinomial,
            Binomial,
            Geometric,
            NegativeBinomial,
            Poisson,
            Skellam,
            PoissonBinomial,
            Beta,
            BetaPrime,
            Biweight,
            Cauchy,
            Chernoff,
            Chi,
            Chisq,
            Cosine,
            Epanechnikov,
            Erlang,
            Exponential,
            FDist,
            Frechet,
            Gamma,
            GeneralizedExtremeValue,
            GeneralizedPareto,
            Gumbel,
            InverseGamma,
            InverseGaussian,
            Kolmogorov,
            Laplace,
            Levy,
            LocationScale,
            Logistic,
            LogitNormal,
            LogNormal,
            Normal,
            NormalCanon,
            NormalInverseGaussian,
            Pareto,
            PGeneralizedGaussian,
            Rayleigh,
            SymTriangularDist,
            TDist,
            TriangularDist,
            Triweight,
            Categorical,
            Truncated,
        )
    eval(getexpr(T))
end
